In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('organized_education_data/public_schools_2020-2021.xlsx',sheet_name = 'Appendix - Historical Data 1979')

In [3]:
df.head(3)

,"APPENDIX: EDUCATION STATISTICS, 1979/1980 to 2021/2022",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Academic Year,Schools,NaN,NaN,NaN,Classes,NaN,NaN,NaN,Students,NaN,NaN,NaN,Staff,NaN,NaN,NaN
1,NaN,Pre,Pri,College,Lycee,Pre,Pri,Lower,Upper,Pre,Pri,Lower,Upper,Pre,Pri,Lower,Upper
2,1979-80,96,n.a,14,1,230,12069,101,7,8229,947317,4803,281,267,13619,205,20

In [4]:
col = ['Academic Year', 'school_pre','school_pri','school_l.sec','school_u.sec',
       'class_pre','class_pri','class_l.sec','class_u.sec',
       'student_pre','student_pri','student_l.sec','student_u.sec',
       'staff_pre','staff_pri','staff_l.sec','staff_u.sec']
df.columns = col
df.head(3)

,Academic Year,school_pre,school_pri,school_l.sec,school_u.sec,class_pre,class_pri,class_l.sec,class_u.sec,student_pre,student_pri,student_l.sec,student_u.sec,staff_pre,staff_pri,staff_l.sec,staff_u.sec
0,Academic Year,Schools,NaN,NaN,NaN,Classes,NaN,NaN,NaN,Students,NaN,NaN,NaN,Staff,NaN,NaN,NaN
1,NaN,Pre,Pri,College,Lycee,Pre,Pri,Lower,Upper,Pre,Pri,Lower,Upper,Pre,Pri,Lower,Upper
2,1979-80,96,n.a,14,1,230,12069,101,7,8229,947317,4803,281,267,13619,205,20

In [5]:
df = df[2:]

In [6]:
df.set_index('Academic Year', inplace=True)

In [7]:
df = df.replace('n.a', np.nan)

C:\Users\ASUS_PC\AppData\Local\Temp\ipykernel_12580\1765892634.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('n.a', np.nan)

In [8]:
df = df.astype(float)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, 1979-80 to 2021-22
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   school_pre     43 non-null     float64
 1   school_pri     41 non-null     float64
 2   school_l.sec   43 non-null     float64
 3   school_u.sec   43 non-null     float64
 4   class_pre      43 non-null     float64
 5   class_pri      43 non-null     float64
 6   class_l.sec    43 non-null     float64
 7   class_u.sec    43 non-null     float64
 8   student_pre    43 non-null     float64
 9   student_pri    43 non-null     float64
 10  student_l.sec  43 non-null     float64
 11  student_u.sec  43 non-null     float64
 12  staff_pre      43 non-null     float64
 13  staff_pri      43 non-null     float64
 14  staff_l.sec    43 non-null     float64
 15  staff_u.sec    43 non-null     float64
dtypes: float64(16)
memory usage: 5.7+ KB

In [10]:
df.to_csv('appendix.csv')

In [12]:
df.shape

(43, 16)